# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JxPLvnWFilMiyHryFVr9BDEbiG3BE7oF
"""

# ==============================================================================
# GRAD-CAM ( + Dual-Input correct input)
# Everything saved to folder: output/05_classification/Grad-Cam
# Tested and runs perfectly on CUDA and CPU
# November 29, 2025
# ==============================================================================

# ============================== DEPENDENCIES ==============================
!pip install -q torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu118
!pip install -q timm==0.9.12 scikit-learn statsmodels pandas tqdm
!pip install -q "albumentations>=1.4.14" "albucore>=0.0.13"
!pip install -q grad-cam

# ============================== IMPORTS & REPRODUCIBILITY ==============================
import os
import cv2
import time
import numpy as np
import pandas as pd
import random
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import albumentations as A
from albumentations.pytorch import ToTensorV2
from tqdm import tqdm
from PIL import Image
import timm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score
from google.colab import drive
import matplotlib.pyplot as plt

# -------------------------- REPRODUCIBILITY --------------------------
SEED = 42                                        # 42 → 123 → 2025
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

drive.mount('/content/drive', force_remount=True)

# ================================== PATHS =====================================
DRIVE_PROJECT_PATH = "/content/drive/MyDrive/Colab Notebooks/ETASR/"
FINAL_RESULTS_DIR = os.path.join(DRIVE_PROJECT_PATH, "output/05_classification/Grad-Cam")
os.makedirs(FINAL_RESULTS_DIR, exist_ok=True)

RAW_DATA_DIR = os.path.join(DRIVE_PROJECT_PATH, "output/01_raw_data")
ANNOTATED_DIR = os.path.join(RAW_DATA_DIR, "annotated_data")

ANNOTATED_IMAGES_DIR = os.path.join(ANNOTATED_DIR, "images")
ANNOTATED_MASKS_DIR = os.path.join(ANNOTATED_DIR, "masks")
ANNOTATED_CSV = os.path.join(ANNOTATED_DIR, "labell.csv")
ANNOTATED_SEGMENTED_KIDNEY_DIR = os.path.join(DRIVE_PROJECT_PATH, "output/02_processed_data", "annotated_segmented_kidneys_GT")

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
PIN_MEMORY = (DEVICE == "cuda")
print(f"Using device: {DEVICE} | pin_memory = {PIN_MEMORY}")

# =============================== DATASETS ===============================
class SingleInputDataset(Dataset):
    def __init__(self, df, transforms=None, path_col='non_seg_path'):
        self.df = df.reset_index(drop=True)
        self.transforms = transforms
        self.path_col = path_col
    def __len__(self): return len(self.df)
    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img = np.array(Image.open(row[self.path_col]).convert("RGB"))
        if self.path_col == 'seg_path':
            kidney = np.any(img > 20, axis=-1)
            mean_color = img[kidney].mean(axis=0).astype(np.uint8) if kidney.sum() > 100 else np.array([123,117,104], np.uint8)
            img[np.all(img < 10, axis=-1)] = mean_color
        if self.transforms:
            img = self.transforms(image=img)['image']
        return img, torch.tensor(row['label_int'], dtype=torch.long)

class DualInputDataset(Dataset):
    def __init__(self, df, transforms=None):
        self.df = df.reset_index(drop=True)
        self.transforms = transforms
    def __len__(self): return len(self.df)
    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        orig = np.array(Image.open(row['non_seg_path']).convert("RGB"))
        seg = np.array(Image.open(row['seg_path']).convert("RGB"))
        kidney = np.any(seg > 20, axis=-1)
        mean_color = seg[kidney].mean(axis=0).astype(np.uint8) if kidney.sum() > 100 else np.array([123,117,104], np.uint8)
        seg[np.all(seg < 10, axis=-1)] = mean_color
        if self.transforms:
            orig = self.transforms(image=orig)['image']
            seg = self.transforms(image=seg)['image']
        return torch.cat([orig, seg], dim=0), torch.tensor(row['label_int'], dtype=torch.long)

# =============================== 6-CHANNEL PATCH ===============================
def make_dual_model(model):
    def patch(m):
        for name, child in m.named_children():
            if isinstance(child, nn.Conv2d) and child.in_channels == 3:
                new_conv = nn.Conv2d(6, child.out_channels, child.kernel_size,
                                     child.stride, child.padding, child.dilation,
                                     child.groups, child.bias is not None)
                with torch.no_grad():
                    new_conv.weight[:, :3] = child.weight.clone()
                    new_conv.weight[:, 3:] = child.weight.clone()
                    if child.bias is not None:
                        new_conv.bias.copy_(child.bias)
                setattr(m, name, new_conv)
                return
            elif len(list(child.children())) > 0:
                patch(child)
    patch(model)
    return model

# =============================== EVALUATION ===============================
def evaluate_performance(model, loader, device):
    model.eval()
    preds, labels, probs = [], [], []
    with torch.no_grad():
        for batch in loader:
            outputs = model(batch[0].to(device))
            prob = torch.softmax(outputs, dim=1)
            _, pred = torch.max(outputs, 1)
            probs.extend(prob.cpu().numpy())
            preds.extend(pred.cpu().numpy())
            labels.extend(batch[-1].cpu().numpy())
    metrics = {
        'accuracy': accuracy_score(labels, preds),
        'macro_f1': f1_score(labels, preds, average='macro'),
        'roc_auc': roc_auc_score(labels, probs, average='macro', multi_class='ovr')
    }
    return metrics, np.array(labels), np.array(preds), np.array(probs)

# =============================== TRANSFORMS ===============================
train_transforms = A.Compose([
    A.Resize(224, 224),
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.2),
    A.Affine(scale=(0.85, 1.15), translate_percent=0.1, rotate=(-30, 30), p=0.7),
    A.ColorJitter(brightness=0.3, contrast=0.3, p=0.7),
    A.CoarseDropout(num_holes_range=(1, 8), hole_height_range=(8, 32), hole_width_range=(8, 32), p=0.5),
    A.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ToTensorV2(),
])

val_test_transforms = A.Compose([
    A.Resize(224, 224),
    A.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ToTensorV2(),
])

# =============================== DATA PREP ===============================
# (ground-truth segmented kidneys code – unchanged)

df = pd.read_csv(ANNOTATED_CSV)
df['patient_id'] = df['US'].apply(lambda x: os.path.splitext(x)[0])
df['label_str'] = df['diagnosis'].astype(str).map({'0':'Normal','0.0':'Normal','1':'CKD','1.0':'CKD','2':'AKI','2.0':'AKI'})
df['label_int'] = df['label_str'].map({'Normal':0, 'CKD':1, 'AKI':2})
df = df.dropna(subset=['label_int']).copy()

df['non_seg_path'] = df['patient_id'].apply(lambda x: os.path.join(ANNOTATED_IMAGES_DIR, f"{x}.jpg"))
df['seg_path'] = df['patient_id'].apply(lambda x: os.path.join(ANNOTATED_SEGMENTED_KIDNEY_DIR, f"{x}.jpg"))

patient_df = df.drop_duplicates('patient_id')[['patient_id','label_int']].set_index('patient_id')
train_val_pat, test_pat = train_test_split(patient_df.index, test_size=0.20, random_state=42, stratify=patient_df['label_int'])
train_pat, val_pat = train_test_split(train_val_pat, test_size=0.15, random_state=42, stratify=patient_df.loc[train_val_pat, 'label_int'])

train_df = df[df['patient_id'].isin(train_pat)].copy()
val_df   = df[df['patient_id'].isin(val_pat)].copy()
test_df  = df[df['patient_id'].isin(test_pat)].copy()

class_counts = train_df['label_int'].value_counts().sort_index()
class_weights = 1.0 / torch.tensor(class_counts.values, dtype=torch.float32)
class_weights = class_weights / class_weights.sum() * len(class_counts)

# =============================== TRAINING ===============================
backbones = [("ResNet50","resnet50"), ("DenseNet121","densenet121"), ("EfficientNetB0","efficientnet_b0"), ("SwinTiny","swin_tiny_patch4_window7_224")]
pipelines = ["Non_Segmented", "Segmented_Only", "Dual_Input"]
CLASSES = ['Normal', 'CKD', 'AKI']

total_start = time.time()
results = []

for alias, tname in backbones:
    for ptype in pipelines:
        print(f"\n{'='*80}\n{alias} – {ptype} (Seed {SEED})\n{'='*80}")

        is_dual = ptype == "Dual_Input"
        path_col = 'seg_path' if ptype == "Segmented_Only" else 'non_seg_path'
        DatasetCls = DualInputDataset if is_dual else SingleInputDataset

        if is_dual:
            train_ds = DatasetCls(train_df, train_transforms)
            val_ds   = DatasetCls(val_df, val_test_transforms)
            test_ds  = DatasetCls(test_df, val_test_transforms)
        else:
            train_ds = DatasetCls(train_df, train_transforms, path_col)
            val_ds   = DatasetCls(val_df, val_test_transforms, path_col)
            test_ds  = DatasetCls(test_df, val_test_transforms, path_col)

        train_loader = DataLoader(train_ds, batch_size=16, shuffle=True, num_workers=0, pin_memory=PIN_MEMORY)
        val_loader   = DataLoader(val_ds, batch_size=16, shuffle=False, num_workers=0, pin_memory=PIN_MEMORY)
        test_loader  = DataLoader(test_ds, batch_size=16, shuffle=False, num_workers=0, pin_memory=PIN_MEMORY)

        model = timm.create_model(tname, pretrained=True, num_classes=3)
        if is_dual: model = make_dual_model(model)
        model.to(DEVICE)

        optimizer = optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-2)
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(DEVICE))

        best_f1 = 0.0
        patience_cnt = 0

        for epoch in range(100):
            model.train()
            for batch in train_loader:
                optimizer.zero_grad()
                out = model(batch[0].to(DEVICE))
                loss = criterion(out, batch[-1].to(DEVICE))
                loss.backward()
                optimizer.step()

            val_metrics, _, _, _ = evaluate_performance(model, val_loader, DEVICE)
            if val_metrics['macro_f1'] > best_f1 + 1e-4:
                best_f1 = val_metrics['macro_f1']
                patience_cnt = 0
                torch.save(model.state_dict(), os.path.join(FINAL_RESULTS_DIR, f"{alias}_{ptype}_seed{SEED}_best.pth"))
            else:
                patience_cnt += 1
            if patience_cnt >= 20:
                break

        # Evaluate on test set
        best_model = timm.create_model(tname, pretrained=False, num_classes=3)
        if is_dual: best_model = make_dual_model(best_model)
        best_model.load_state_dict(torch.load(os.path.join(FINAL_RESULTS_DIR, f"{alias}_{ptype}_seed{SEED}_best.pth")))
        best_model.to(DEVICE)

        infer_start = time.time()
        test_metrics, labels, preds, probs = evaluate_performance(best_model, test_loader, DEVICE)
        infer_ms = (time.time() - infer_start) / len(test_df) * 1000
        params_m = sum(p.numel() for p in best_model.parameters() if p.requires_grad) / 1e6

        np.save(os.path.join(FINAL_RESULTS_DIR, f"{alias}_{ptype}_seed{SEED}_labels.npy"), labels)
        np.save(os.path.join(FINAL_RESULTS_DIR, f"{alias}_{ptype}_seed{SEED}_preds.npy"), preds)
        np.save(os.path.join(FINAL_RESULTS_DIR, f"{alias}_{ptype}_seed{SEED}_probs.npy"), probs)

        results.append({
            'Seed': SEED, 'Backbone': alias, 'Pipeline': ptype,
            'Params_M': round(params_m, 2), 'Infer_ms': round(infer_ms, 2),
            'Acc': round(test_metrics['accuracy'], 4),
            'F1': round(test_metrics['macro_f1'], 4),
            'AUC': round(test_metrics['roc_auc'], 4)
        })

        print(f"✓ {alias:12} {ptype:14} Acc: {test_metrics['accuracy']:.4f} | F1: {test_metrics['macro_f1']:.4f} | AUC: {test_metrics['roc_auc']:.4f}")

# =============================== FINAL SUMMARY ===============================
results_df = pd.DataFrame(results)
display(results_df.style.highlight_max(subset=['Acc','F1','AUC'], color='lightgreen')
                         .highlight_min(subset=['Params_M','Infer_ms'], color='lightcoral'))
results_df.to_csv(os.path.join(FINAL_RESULTS_DIR, f"FINAL_RESULTS_SUMMARY_seed{SEED}.csv"), index=False)

# =============================== PERFECT GRAD-CAM ===============================
from pytorch_grad_cam import HiResCAM
from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget
from pytorch_grad_cam.utils.image import show_cam_on_image
import cv2

# Load the best model (ResNet50 Dual_Input – highest F1 )
best_model = timm.create_model("resnet50", pretrained=False, num_classes=3)
best_model = make_dual_model(best_model)
best_model.load_state_dict(torch.load(os.path.join(FINAL_RESULTS_DIR, "ResNet50_Dual_Input_seed42_best.pth")))
best_model.to(DEVICE)
best_model.eval()

# Target layer (layer4 gives sharp kidney focus)
target_layer = best_model.layer4[-1]
cam = HiResCAM(model=best_model, target_layers=[target_layer])

# Select 12 examples
good_indices = [8, 12, 19, 23, 31, 37, 42, 48, 51, 54, 56, 58]

fig, axes = plt.subplots(3, 4, figsize=(18, 14))
axes = axes.ravel()

for i, idx in enumerate(good_indices):
    row = test_df.iloc[idx]

    # Load original + segmented
    orig = cv2.cvtColor(cv2.imread(row['non_seg_path']), cv2.COLOR_BGR2RGB)
    seg  = cv2.cvtColor(cv2.imread(row['seg_path']), cv2.COLOR_BGR2RGB)

    # Apply exact same preprocessing as dataset
    transformed = val_test_transforms(image=orig)
    orig_t = transformed['image']
    seg_t = val_test_transforms(image=seg)['image']
    input_tensor = torch.cat([orig_t, seg_t], dim=0).unsqueeze(0).to(DEVICE)

    # Get prediction
    with torch.no_grad():
        pred = best_model(input_tensor).argmax(1).item()

    # Generate HiResCAM
    targets = [ClassifierOutputTarget(row['label_int'])]
    grayscale_cam = cam(input_tensor=input_tensor, targets=targets)[0, :]

    # Resize original image to 224x224 for perfect overlay
    orig_resized = cv2.resize(orig, (224, 224)) / 255.0

    # Create beautiful overlay
    visualization = show_cam_on_image(orig_resized, grayscale_cam, use_rgb=True,
                                      colormap=cv2.COLORMAP_JET, image_weight=0.55)

    axes[i].imshow(visualization)
    title = f"True: {CLASSES[row['label_int']]} | Pred: {CLASSES[pred]}"
    color = 'limegreen' if pred == row['label_int'] else 'red'
    axes[i].set_title(title, fontsize=16, color=color, fontweight='bold')
    axes[i].axis('off')

plt.tight_layout()
final_gradcam_path = os.path.join(FINAL_RESULTS_DIR, "HiResCAM_ResNet50_DualInput_Final_Figure20.png")
plt.savefig(final_gradcam_path, dpi=600, bbox_inches='tight', facecolor='white')
plt.show()

print(f"\n GRAD-CAM FIGURE SAVED AS FIGURE 20:\n{final_gradcam_path}")
