# -*- coding: utf-8 -*-
"""kidney_disease_classification_unet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vc7rhnly271nDOOu7Atn2vMsBSeWZJEc
"""

#!/usr/bin/env python3
"""
Classify kidney conditions (Normal, CKD, AKI) using segmented kidney images.

This script trains classification models (e.g., ResNet50) on segmented kidneys,
evaluates performance, and saves results as metrics and visualizations.
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import albumentations as A
from albumentations.pytorch import ToTensorV2
from tqdm import tqdm
import timm
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, f1_score, accuracy_score
from pathlib import Path

# Configuration
DRIVE_PROJECT_PATH = "data"
RAW_DATA_DIR = os.path.join(DRIVE_PROJECT_PATH, "raw_data")
PROCESSED_DATA_DIR = os.path.join(DRIVE_PROJECT_PATH, "processed_data")
MODEL_TRAINING_DIR = os.path.join(DRIVE_PROJECT_PATH, "model_training")
OUTPUT_DIR = os.path.join(DRIVE_PROJECT_PATH, "classification_outputs")
OUTPUT_SSNET_DIR = os.path.join(OUTPUT_DIR, "ssmunet_based")
ANNOTATED_DATA_DIR = os.path.join(RAW_DATA_DIR, "annotated_data")
ANNOTATED_IMAGES_DIR = os.path.join(ANNOTATED_DATA_DIR, "images")
ANNOTATED_CSV_PATH = os.path.join(ANNOTATED_DATA_DIR, "labell.csv")
UNANNOTATED_IMAGES_PARENT_DIR = os.path.join(RAW_DATA_DIR, "unannotated_data", "images")
SEGMENTATION_MODEL_PATH = os.path.join(MODEL_TRAINING_DIR, "ssmunet_models", "student_model_best.pth")
ANNOTATED_SEGMENTED_KIDNEY_DIR = os.path.join(PROCESSED_DATA_DIR, "annotated_segmented_kidneys")
PRETRAINED_MODEL_DIR = os.path.join(OUTPUT_SSNET_DIR, "stage2_kidney_expert_models")
FINAL_RESULTS_DIR = os.path.join(OUTPUT_SSNET_DIR, "stage3_final_results")
Path(ANNOTATED_SEGMENTED_KIDNEY_DIR).mkdir(parents=True, exist_ok=True)
Path(PRETRAINED_MODEL_DIR).mkdir(parents=True, exist_ok=True)
Path(FINAL_RESULTS_DIR).mkdir(parents=True, exist_ok=True)
CLS_IMG_SIZE = 224
BATCH_SIZE = 16
EPOCHS = 100
PATIENCE = 20
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
CLASSES = ['Normal', 'CKD', 'AKI']
label_map_to_int = {'Normal': 0, 'CKD': 1, 'AKI': 2}
print(f"Using device: {DEVICE}")

# Augmentation Pipelines
train_transforms = A.Compose([
    A.Resize(CLS_IMG_SIZE, CLS_IMG_SIZE),
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.2),
    A.Affine(scale=(0.85, 1.15), translate_percent=0.1, rotate=(-30, 30), p=0.7),
    A.ColorJitter(brightness=0.3, contrast=0.3, p=0.7),
    A.CoarseDropout(max_holes=8, max_height=16, max_width=16, p=0.5),
    A.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ToTensorV2(),
])
val_test_transforms = A.Compose([
    A.Resize(CLS_IMG_SIZE, CLS_IMG_SIZE),
    A.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ToTensorV2(),
])

class SingleInputDataset(Dataset):
    def __init__(self, df, transforms):
        self.df = df.reset_index(drop=True)
        self.transforms = transforms
    def __len__(self):
        return len(self.df)
    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        image = np.array(Image.open(row['image_path']).convert("RGB"))
        label = torch.tensor(int(row['label']), dtype=torch.long)
        if self.transforms:
            image = self.transforms(image=image)['image']
        return image, label

class DualInputDataset(Dataset):
    def __init__(self, df, transforms):
        self.df = df.reset_index(drop=True)
        self.transforms = transforms
        self.resize_op = A.Resize(height=CLS_IMG_SIZE, width=CLS_IMG_SIZE)
        if self.transforms:
            self.dual_transform = A.Compose(transforms.transforms, additional_targets={'image2': 'image'})
    def __len__(self):
        return len(self.df)
    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        image1 = np.array(Image.open(row['non_seg_path']).convert("RGB"))
        image2 = np.array(Image.open(row['seg_path']).convert("RGB"))
        label = torch.tensor(int(row['label']), dtype=torch.long)
        image1 = self.resize_op(image=image1)['image']
        image2 = self.resize_op(image=image2)['image']
        if self.transforms:
            transformed = self.dual_transform(image=image1, image2=image2)
            image1, image2 = transformed['image'], transformed['image2']
        return image1, image2, label

def evaluate_performance(model, loader, criterion, device):
    """Evaluate model performance on a dataset."""
    model.eval()
    total_loss, correct, total = 0, 0, 0
    all_labels, all_preds = [], []
    with torch.no_grad():
        for data in loader:
            labels = data[-1].to(device)
            inputs = [d.to(device) for d in data[:-1]]
            outputs = model(*inputs)
            loss = criterion(outputs, labels)
            total_loss += loss.item() * labels.size(0)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
            all_labels.extend(labels.cpu().numpy())
            all_preds.extend(predicted.cpu().numpy())
    accuracy = correct / total if total > 0 else 0
    macro_f1 = f1_score(all_labels, all_preds, average='macro')
    return {'loss': total_loss / total if total > 0 else 0, 'accuracy': accuracy, 'macro_f1': macro_f1}, all_labels, all_preds

def plot_history(history, experiment_name):
    """Plot training and validation loss and accuracy."""
    plt.figure(figsize=(18, 6))
    plt.subplot(1, 2, 1)
    plt.plot(history['train_loss'], label='Training Loss')
    plt.plot(history['val_loss'], label='Validation Loss')
    plt.title(f'{experiment_name} - Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)
    plt.subplot(1, 2, 2)
    plt.plot(history['train_acc'], label='Training Accuracy')
    plt.plot(history['val_acc'], label='Validation Accuracy')
    plt.title(f'{experiment_name} - Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy (%)')
    plt.legend()
    plt.grid(True)
    plt.savefig(os.path.join(FINAL_RESULTS_DIR, f"{experiment_name}_history.png"))
    plt.close()

def main():
    """Train and evaluate classification models."""
    print("--- Classification Pipeline for Kidney Disease ---")
    df = pd.read_csv(ANNOTATED_CSV_PATH)
    df['image_path'] = df['image_path'].apply(lambda x: os.path.join(ANNOTATED_IMAGES_DIR, x))
    df['seg_path'] = df['image_path'].apply(lambda x: os.path.join(ANNOTATED_SEGMENTED_KIDNEY_DIR, os.path.basename(x)))
    df['non_seg_path'] = df['image_path']
    df['label'] = df['label'].map(label_map_to_int)

    train_df, temp_df = train_test_split(df, test_size=0.3, stratify=df['label'], random_state=42)
    val_df, test_df = train_test_split(temp_df, test_size=0.5, stratify=temp_df['label'], random_state=42)

    # TODO: Implement dataset and dataloader
    # Example:
    # train_dataset = DualInputDataset(train_df, train_transforms)
    # val_dataset = DualInputDataset(val_df, val_test_transforms)
    # test_dataset = DualInputDataset(test_df, val_test_transforms)
    # train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
    # val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE)
    # test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE)

    final_results = []
    model_configs = [
        {'model_class': lambda model_name, num_classes: timm.create_model(model_name, pretrained=True, num_classes=num_classes),
         'model_name': 'resnet50', 'input_type': 'single', 'experiment_name': 'resnet50_single'},
        # Add other configurations as needed
    ]

    for config in model_configs:
        experiment_name = config['experiment_name']
        model = config['model_class'](model_name=config['model_name'], num_classes=len(CLASSES)).to(DEVICE)
        optimizer = optim.Adam(model.parameters(), lr=1e-4)
        criterion = nn.CrossEntropyLoss()
        history = {'train_loss': [], 'val_loss': [], 'train_acc': [], 'val_acc': [], 'val_metrics_list': []}
        best_val_f1 = 0.0
        patience_counter = 0

        # TODO: Implement training loop
        # Example:
        # for epoch in range(EPOCHS):
        #     model.train()
        #     total_train_loss, train_correct, train_total = 0, 0, 0
        #     for data in tqdm(train_loader, desc=f"Epoch {epoch+1}/{EPOCHS}"):
        #         labels = data[-1].to(DEVICE)
        #         inputs = [d.to(DEVICE) for d in data[:-1]]
        #         optimizer.zero_grad()
        #         outputs = model(*inputs)
        #         loss = criterion(outputs, labels)
        #         loss.backward()
        #         optimizer.step()
        #         total_train: loss += loss.item() * labels.size(0)
        #         _, predicted = torch.max(outputs.data, 1)
        #         train_total += labels.size(0)
        #         train_correct += (predicted == labels).sum().item()

        print(f"\n--- Final Evaluation on Test Set for {experiment_name} ---")
        test_metrics, test_labels, test_preds = evaluate_performance(model, test_loader, criterion, DEVICE)
        final_train_metrics, _, _ = evaluate_performance(model, train_loader, criterion, DEVICE)
        best_epoch_idx = np.argmax([m['macro_f1'] for m in history['val_metrics_list']]) if history['val_metrics_list'] else -1
        best_val_metrics = history['val_metrics_list'][best_epoch_idx] if best_epoch_idx != -1 else None

        final_results.append({
            'Experiment': experiment_name,
            'Train Accuracy': final_train_metrics['accuracy'],
            'Train F1 (Macro)': final_train_metrics['macro_f1'],
            'Val Accuracy (at best F1)': best_val_metrics['accuracy'] if best_val_metrics else None,
            'Val F1 (Macro - Best)': best_val_metrics['macro_f1'] if best_val_metrics else None,
            'Test Accuracy': test_metrics['accuracy'],
            'Test F1 (Macro)': test_metrics['macro_f1']
        })

        cm = confusion_matrix(test_labels, test_preds)
        disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=CLASSES)
        disp.plot(cmap=plt.cm.Blues)
        plt.title(f"Confusion Matrix - {experiment_name}")
        plt.savefig(os.path.join(FINAL_RESULTS_DIR, f"{experiment_name}_confusion_matrix.png"))
        plt.close()

    if final_results:
        results_df = pd.DataFrame(final_results)
        results_df = results_df.set_index('Experiment')
        results_df.to_csv(os.path.join(FINAL_RESULTS_DIR, "final_comparison_metrics.csv"))
        print(f"\nFull comparison saved to {os.path.join(FINAL_RESULTS_DIR, 'final_comparison_metrics.csv')}")

if __name__ == "__main__":
    main()