# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JxPLvnWFilMiyHryFVr9BDEbiG3BE7oF
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

!pip install ptflops --quiet

import os
import numpy as np
import pandas as pd
import torch
import timm
from ptflops import get_model_complexity_info
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score
from scipy.stats import binomtest
import time

FINAL_RESULTS_DIR = "/content/drive/MyDrive/......"
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# ============================ COLLECT ALL PREDICTIONS ============================
data = {}
for file in os.listdir(FINAL_RESULTS_DIR):
    if not file.endswith("_test_labels.npy"):
        continue
    base = file.replace("_test_labels.npy", "")
    labels = np.load(os.path.join(FINAL_RESULTS_DIR, file))
    preds  = np.load(os.path.join(FINAL_RESULTS_DIR, base + "_test_preds.npy"))
    probs  = np.load(os.path.join(FINAL_RESULTS_DIR, base + "_test_probs.npy"))

    backbone = base.split("_")[0]
    if backbone == "EfficientNetB0": backbone = "EfficientNetB0"
    if backbone == "SwinTiny": backbone = "SwinTiny"
    input_type = "Dual" if "Dual" in base else "Single"

    key = f"{backbone}_{input_type}"
    data[key] = {
        "labels": labels,
        "preds": preds,
        "probs": probs,
        "acc": accuracy_score(labels, preds),
        "f1": f1_score(labels, preds, average='macro'),
        "auc": roc_auc_score(labels, probs, average='macro', multi_class='ovr')
    }

# ============================ TABLE – STATISTICAL COMPARISON ============================
results = []
for key in sorted(data.keys()):
    d = data[key]
    results.append({
        "Backbone": key.split("_")[0],
        "Input": key.split("_")[1],
        "Accuracy": f"{d['acc']:.4f}",
        "Macro F1": f"{d['f1']:.4f}",
        "Macro AUC": f"{d['auc']:.4f}",
        "McNemar p": "—",
        "DeLong p": "—"
    })

# Paired tests
for bb in ["ResNet50", "DenseNet121", "EfficientNetB0", "SwinTiny"]:
    s_key = f"{bb}_Single"
    d_key = f"{bb}_Dual"
    if s_key not in data or d_key not in data:
        continue

    y = data[s_key]["labels"]
    pred_s = data[s_key]["preds"]
    prob_s = data[s_key]["probs"]
    pred_d = data[d_key]["preds"]
    prob_d = data[d_key]["probs"]

    # McNemar
    b = np.sum((pred_s == y) & (pred_d != y))
    c = np.sum((pred_s != y) & (pred_d == y))
    mcnemar_p = binomtest(min(b,c), b+c, 0.5).pvalue if b+c > 0 else 1.0

    # DeLong bootstrap
    diffs = []
    for _ in range(10000):
        idx = np.random.choice(len(y), len(y), replace=True)
        if len(np.unique(y[idx])) < 3:
            continue
        try:
            a1 = roc_auc_score(y[idx], prob_s[idx], average='macro', multi_class='ovr')
            a2 = roc_auc_score(y[idx], prob_d[idx], average='macro', multi_class='ovr')
            diffs.append(a2 - a1)
        except:
            continue
    delong_p = 2 * min(np.mean(np.array(diffs) >= 0), np.mean(np.array(diffs) <= 0)) if diffs else 1.0

    stars = "***" if mcnemar_p < 0.001 else "**" if mcnemar_p < 0.01 else "*" if mcnemar_p < 0.05 else ""

    for row in results:
        if row["Backbone"] == bb and row["Input"] == "Dual":
            row["McNemar p"] = f"{mcnemar_p:.4f}{stars}"
            row["DeLong p"]   = f"{delong_p:.4f}{stars}"

df_table5 = pd.DataFrame(results)
print("\n=== TABLE 5 – Statistical Comparison (test set n=59) ===")
display(df_table5.style.background_gradient(cmap='Greens', subset=['Accuracy', 'Macro F1', 'Macro AUC']))

# ============================ TABLE  – COMPUTATIONAL METRICS  ============================
timm_names = {
    "ResNet50": "resnet50",
    "DenseNet121": "densenet121",
    "EfficientNetB0": "efficientnet_b0",
    "SwinTiny": "swin_tiny_patch4_window7_224"
}

def make_dual_model(model):
    for name, m in model.named_modules():
        if isinstance(m, torch.nn.Conv2d) and m.in_channels == 3:
            new = torch.nn.Conv2d(6, m.out_channels, m.kernel_size, m.stride, m.padding,
                                  m.dilation, m.groups, bias=m.bias is not None)
            with torch.no_grad():
                new.weight[:, :3] = m.weight.clone()
                new.weight[:, 3:] = m.weight.clone()
                if m.bias is not None: new.bias.copy_(m.bias)
            parent = dict(model.named_modules())[name.rsplit('.',1)[0]] if '.' in name else model
            setattr(parent, name.split('.')[-1], new)
            return model
    return model

comp_results = []
for file in sorted(os.listdir(FINAL_RESULTS_DIR)):
    if not file.endswith("_best.pth"):
        continue
    base = file.replace("_best.pth", "")
    backbone = base.split("_")[0]
    if backbone not in timm_names: continue

    model = timm.create_model(timm_names[backbone], pretrained=False, num_classes=3)
    if "Dual" in base:
        model = make_dual_model(model)

    state = torch.load(os.path.join(FINAL_RESULTS_DIR, file), map_location='cpu')
    model.load_state_dict(state)
    model.to(DEVICE)
    model.eval()

    channels = 6 if "Dual" in base else 3
    input_sz = (channels, 224, 224)

    macs, params = get_model_complexity_info(model, input_sz, as_strings=False, print_per_layer_stat=False)
    flops = 2 * macs / 1e9

    if DEVICE == "cuda":
        torch.cuda.reset_peak_memory_stats()
    with torch.no_grad():
        _ = model(torch.randn(1, *input_sz).to(DEVICE))
    memory = torch.cuda.max_memory_allocated() / 1024**3 if DEVICE == "cuda" else "CPU"

    x = torch.randn(1, *input_sz).to(DEVICE)
    if DEVICE == "cuda": torch.cuda.synchronize()
    start = time.time()
    for _ in range(200):
        with torch.no_grad(): _ = model(x)
    if DEVICE == "cuda": torch.cuda.synchronize()
    inf_time = (time.time() - start) / 200 * 1000

    comp_results.append({
        "Model": backbone,
        "Input": "Dual" if "Dual" in base else "Single",
        "Params (M)": round(params / 1e6, 2),
        "GFLOPs": round(flops, 2),
        "Peak Memory (GB)": f"{memory:.1f}" if isinstance(memory, float) else memory,
        "Inference (ms/image)": round(inf_time, 1)
    })

df_table7 = pd.DataFrame(comp_results)
print("\n=== TABLE  – Computational Efficiency (live measured on final models) ===")
display(df_table7)
