# -*- coding: utf-8 -*-
"""train_teacher_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RjQ4NFEp1LH6gNMY_1rBYXT4H5sofdWw
"""

"""
Train a U-Net model (teacher) for kidney segmentation using annotated data.

This script sets up a data pipeline, trains the U-Net model, and evaluates its
performance using metrics like Dice coefficient, IoU, and pixel accuracy. Results
are saved as plots and a metrics CSV file.
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from tqdm import tqdm
import pandas as pd
from sklearn.metrics import confusion_matrix
from pathlib import Path

# Configuration
DATA_DIR = "data/raw_data"
IMAGE_DIR = os.path.join(DATA_DIR, "images")
MASK_DIR = os.path.join(DATA_DIR, "masks")
RESULTS_DIR = "results"
MODEL_DIR = os.path.join(RESULTS_DIR, "models")
Path(RESULTS_DIR).mkdir(parents=True, exist_ok=True)
Path(MODEL_DIR).mkdir(parents=True, exist_ok=True)
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
BATCH_SIZE = 8
NUM_EPOCHS = 150

# Placeholder for U-Net architecture
class UNet(nn.Module):
    def __init__(self):
        super(UNet, self).__init__()
        # TODO: Define U-Net architecture (encoder-decoder with skip connections)
        # Example structure:
        # - Encoder: Conv2d, BatchNorm, ReLU, MaxPool
        # - Decoder: Conv2d, BatchNorm, ReLU, UpSample
        # - Skip connections between encoder and decoder
        # Refer to original notebook for complete implementation
        pass

    def forward(self, x):
        # TODO: Implement forward pass
        pass

#----------------------
# Architecture 1: Standard U-Net   # uncomment if U-NET MODEL is used
#----------------------
# class UNet(nn.Module):
#     def __init__(self, in_channels=3, out_channels=1, features=[64, 128, 256, 512]):
#         super().__init__()
#         self.ups = nn.ModuleList()
#         self.downs = nn.ModuleList()
#         self.pool = nn.MaxPool2d(kernel_size=2, stride=2)

#         # Down part of UNet
#         for feature in features:
#             self.downs.append(ConvBlock(in_channels, feature))
#             in_channels = feature

#         # Up part of UNet
#         for feature in reversed(features):
#             self.ups.append(nn.ConvTranspose2d(feature * 2, feature, kernel_size=2, stride=2))
#             self.ups.append(ConvBlock(feature * 2, feature))

#         self.bottleneck = ConvBlock(features[-1], features[-1] * 2)
#         self.final_conv = nn.Conv2d(features[0], out_channels, kernel_size=1)

#     def forward(self, x):
#         skip_connections = []
#         for down in self.downs:
#             x = down(x)
#             skip_connections.append(x)
#             x = self.pool(x)

#         x = self.bottleneck(x)
#         skip_connections = skip_connections[::-1]

#         for idx in range(0, len(self.ups), 2):
#             x = self.ups[idx](x)
#             skip_connection = skip_connections[idx // 2]
#             if x.shape != skip_connection.shape:
#                 x = torch.nn.functional.interpolate(x, size=skip_connection.shape[2:])
#             concat_skip = torch.cat((skip_connection, x), dim=1)
#             x = self.ups[idx + 1](concat_skip)

#         return self.final_conv(x)
#-------------------------------
# Architecture 2: Modified U-Net with Heavy Dropout  # Uncomment if Modified is used
#-----------------
# class ModifiedUNet(nn.Module):
#     """PyTorch implementation of the user-provided Keras U-Net architecture."""
#     def __init__(self, in_channels=3, out_channels=1):
#         super().__init__()
#         # Encoder
#         self.c0 = ConvBlock(in_channels, 64, num_convs=2)
#         self.m0 = nn.MaxPool2d(2, 2); self.d0 = nn.Dropout(0.3)
#         self.c1 = ConvBlock(64, 128, num_convs=2)
#         self.m1 = nn.MaxPool2d(2, 2); self.d1 = nn.Dropout(0.4)
#         self.c2 = ConvBlock(128, 256, num_convs=3)
#         self.m2 = nn.MaxPool2d(2, 2); self.d2 = nn.Dropout(0.4)
#         self.c3 = ConvBlock(256, 512, num_convs=3)
#         self.m3 = nn.MaxPool2d(2, 2); self.d3 = nn.Dropout(0.5)

#         # Bottleneck
#         self.c4 = ConvBlock(512, 512, num_convs=3)
#         self.m4 = nn.MaxPool2d(2, 2); self.d4 = nn.Dropout(0.4)
#         # Decoder
#         self.dc0 = nn.ConvTranspose2d(512, 512, 3, 2, 1, 1); self.d5 = nn.Dropout(0.5)
#         self.dec0 = ConvBlock(1024, 512, num_convs=2) # 512 + 512
#         self.dc1 = nn.ConvTranspose2d(512, 256, 3, 2, 1, 1); self.d6 = nn.Dropout(0.5)
#         self.dec1 = ConvBlock(768, 256, num_convs=2) # 256 + 512
#         self.dc2 = nn.ConvTranspose2d(256, 128, 3, 2, 1, 1); self.d7 = nn.Dropout(0.5)
#         self.dec2 = ConvBlock(384, 128, num_convs=2) # 128 + 256
#         self.dc3 = nn.ConvTranspose2d(128, 64, 3, 2, 1, 1); self.d8 = nn.Dropout(0.5)
#         self.dec3 = ConvBlock(192, 64, num_convs=2) # 64 + 128
#         self.dc4 = nn.ConvTranspose2d(64, 32, 3, 2, 1, 1); self.d9 = nn.Dropout(0.5)
#         self.dec4 = ConvBlock(96, 32, num_convs=1) # 32 + 64
#         self.final_conv = nn.Conv2d(32, out_channels, 1)
#     def forward(self, x):
#         c0 = self.c0(x); p0 = self.d0(self.m0(c0))
#         c1 = self.c1(p0); p1 = self.d1(self.m1(c1))
#         c2 = self.c2(p1); p2 = self.d2(self.m2(c2))
#         c3 = self.c3(p2); p3 = self.d3(self.m3(c3))
#         c4 = self.c4(p3); p4 = self.d4(self.m4(c4))
#         dc0 = self.dc0(p4); cat0 = torch.cat([dc0, c4], dim=1); dec0 = self.dec0(self.d5(cat0))
#         dc1 = self.dc1(dec0); cat1 = torch.cat([dc1, c3], dim=1); dec1 = self.dec1(self.d6(cat1))
#         dc2 = self.dc2(dec1); cat2 = torch.cat([dc2, c2], dim=1); dec2 = self.dec2(self.d7(cat2))
#         dc3 = self.dc3(dec2); cat3 = torch.cat([dc3, c1], dim=1); dec3 = self.dec3(self.d8(cat3))
#         dc4 = self.dc4(dec3); cat4 = torch.cat([dc4, c0], dim=1); dec4 = self.dec4(self.d9(cat4))
#         return self.final_conv(dec4)
#-----------------------------------
# Architecture 3: ATTENTION U-NET MODEL   # Uncomment if ATTENTION U-NET MODEL is used
#-----------------------------------
# class AttentionGate(nn.Module):
#     def __init__(self, F_g, F_l, F_int):
#         super().__init__()
#         self.W_g = nn.Sequential(nn.Conv2d(F_g, F_int, 1, 1, 0, bias=True), nn.BatchNorm2d(F_int))
#         self.W_x = nn.Sequential(nn.Conv2d(F_l, F_int, 1, 1, 0, bias=True), nn.BatchNorm2d(F_int))
#         self.psi = nn.Sequential(nn.Conv2d(F_int, 1, 1, 1, 0, bias=True), nn.BatchNorm2d(1), nn.Sigmoid())
#         self.relu = nn.ReLU(inplace=True)
#     def forward(self, g, x):
#         g1 = self.W_g(g); x1 = self.W_x(x); psi = self.relu(g1 + x1); psi = self.psi(psi)
#         return x * psi

# class AttentionUNet(nn.Module):
#     def __init__(self, in_channels=3, out_channels=1):
#         super().__init__()
#         features = [64, 128, 256, 512, 1024]
#         self.pool = nn.MaxPool2d(2, 2)
#         self.encoder1 = ConvBlock(in_channels, features[0]); self.encoder2 = ConvBlock(features[0], features[1])
#         self.encoder3 = ConvBlock(features[1], features[2]); self.encoder4 = ConvBlock(features[2], features[3])
#         self.bottleneck = ConvBlock(features[3], features[4])
#         self.upconv4 = nn.ConvTranspose2d(features[4], features[3], 2, 2); self.att4 = AttentionGate(features[3], features[3], features[2]); self.decoder4 = ConvBlock(features[4], features[3])
#         self.upconv3 = nn.ConvTranspose2d(features[3], features[2], 2, 2); self.att3 = AttentionGate(features[2], features[2], features[1]); self.decoder3 = ConvBlock(features[3], features[2])
#         self.upconv2 = nn.ConvTranspose2d(features[2], features[1], 2, 2); self.att2 = AttentionGate(features[1], features[1], features[0]); self.decoder2 = ConvBlock(features[2], features[1])
#         self.upconv1 = nn.ConvTranspose2d(features[1], features[0], 2, 2); self.att1 = AttentionGate(features[0], features[0], 32); self.decoder1 = ConvBlock(features[1], features[0])
#         self.final_conv = nn.Conv2d(features[0], out_channels, 1)
#     def forward(self, x):
#         enc1 = self.encoder1(x); enc2 = self.encoder2(self.pool(enc1)); enc3 = self.encoder3(self.pool(enc2)); enc4 = self.encoder4(self.pool(enc3))
#         bottleneck = self.bottleneck(self.pool(enc4))
#         up4 = self.upconv4(bottleneck); att4 = self.att4(g=up4, x=enc4); dec4 = self.decoder4(torch.cat((att4, up4), dim=1))
#         up3 = self.upconv3(dec4); att3 = self.att3(g=up3, x=enc3); dec3 = self.decoder3(torch.cat((att3, up3), dim=1))
#         up2 = self.upconv2(dec3); att2 = self.att2(g=up2, x=enc2); dec2 = self.decoder2(torch.cat((att2, up2), dim=1))
#         up1 = self.upconv1(dec2); att1 = self.att1(g=up1, x=enc1); dec1 = self.decoder1(torch.cat((att1, up1), dim=1))
#         return self.final_conv(dec1)
# def denormalize(tensor):
    """
    Denormalize image tensor for visualization.

    Args:
        tensor (np.ndarray): Normalized image tensor.

    Returns:
        np.ndarray: Denormalized image.
    """
    mean = np.array([0.485, 0.456, 0.406])
    std = np.array([0.229, 0.224, 0.225])
    tensor = tensor.transpose((1, 2, 0))
    tensor = std * tensor + mean
    return np.clip(tensor, 0, 1)

def compute_metrics(y_true, y_pred):
    """
    Compute evaluation metrics for segmentation.

    Args:
        y_true (np.ndarray): Ground truth masks.
        y_pred (np.ndarray): Predicted masks.

    Returns:
        tuple: Accuracy, IoU, and Dice coefficient.
    """
    accuracy = np.mean(y_true.flatten() == y_pred.flatten()) * 100
    y_true_sq, y_pred_sq = np.squeeze(y_true), np.squeeze(y_pred)
    intersection = np.sum(y_true_sq * y_pred_sq, axis=(1, 2))
    union = np.sum(y_true_sq, axis=(1, 2)) + np.sum(y_pred_sq, axis=(1, 2)) - intersection
    iou = np.mean(intersection / (union + 1e-6))
    dice = np.mean((2. * intersection) / (np.sum(y_true_sq, axis=(1, 2)) + np.sum(y_pred_sq, axis=(1, 2)) + 1e-6))
    return accuracy, iou, dice

def plot_segmentation_examples(images, true_masks, pred_masks, num_examples=5):
    """
    Plot segmentation examples for visualization.

    Args:
        images (np.ndarray): Input images.
        true_masks (np.ndarray): Ground truth masks.
        pred_masks (np.ndarray): Predicted masks.
        num_examples (int): Number of examples to plot.
    """
    indices = np.random.choice(len(images), num_examples, replace=False)
    for idx in indices:
        fig, axes = plt.subplots(1, 3, figsize=(15, 5))
        axes[0].imshow(denormalize(images[idx]))
        axes[0].set_title('Input Image')
        axes[0].axis('off')
        axes[1].imshow(true_masks[idx].squeeze(), cmap='gray')
        axes[1].set_title('Ground Truth')
        axes[1].axis('off')
        axes[2].imshow(pred_masks[idx].squeeze(), cmap='gray')
        axes[2].set_title('Predicted Mask')
        axes[2].axis('off')
        plt.tight_layout()
        plt.savefig(os.path.join(RESULTS_DIR, f'segmentation_example_{idx}.png'))
        plt.close()

def plot_confusion_matrix(y_true, y_pred):
    """
    Plot confusion matrix for segmentation predictions.

    Args:
        y_true (np.ndarray): Ground truth masks.
        y_pred (np.ndarray): Predicted masks.
    """
    cm = confusion_matrix(y_true.flatten(), y_pred.flatten())
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Background', 'Kidney'],
                yticklabels=['Background', 'Kidney'])
    plt.title('Pixel-Wise Confusion Matrix')
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')
    plt.savefig(os.path.join(RESULTS_DIR, 'confusion_matrix.png'))
    plt.close()

def main():
    """Train the teacher U-Net model and evaluate its performance."""
    print(f"--- Training the 'Teacher' Model on Annotated Data ---")
    print(f"Using device: {DEVICE}")

    # TODO: Implement data loading
    # Example: Use torchvision.datasets.ImageFolder or custom Dataset class
    # Expected split: 198 training, 36 validation, 59 test images
    # Refer to original notebook for stratified patient-level split
    # Placeholder: train_loader, val_loader, test_loader = ...

    model = UNet().to(DEVICE)
    # TODO: Define loss function, optimizer, and training loop
    # Example:
    # criterion = nn.BCEWithLogitsLoss()
    # optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
    # for epoch in range(NUM_EPOCHS):
    #     # Training and validation loops
    #     # Save metrics to history
    history = {'train_loss': [], 'val_loss': [], 'train_acc': [], 'val_acc': [], 'val_dice': []}

    # Placeholder for test evaluation
    all_true_masks, all_pred_masks, all_images = [], [], []
    # TODO: Implement test loop
    # Example:
    # model.eval()
    # with torch.no_grad():
    #     for images, masks in tqdm(test_loader, desc="Generating Test Predictions"):
    #         images_gpu = images.to(DEVICE)
    #         outputs = model(images_gpu)
    #         preds = torch.sigmoid(outputs) > 0.5
    #         all_pred_masks.append(preds.cpu())
    #         all_true_masks.append(masks)
    #         all_images.append(images)

    # Compute metrics
    all_true_masks = np.array(all_true_masks)
    all_pred_masks = np.array(all_pred_masks).astype(int)
    all_images = np.array(all_images)
    accuracy, iou, dice = compute_metrics(all_true_masks, all_pred_masks)
    test_metrics = {'loss': 0.0, 'accuracy': accuracy, 'iou': iou, 'dice': dice}

    # Save metrics
    final_metrics_summary = {
        'Best Val Dice': [max(history['val_dice']) if history['val_dice'] else None],
        'Best Val Loss': [min(history['val_loss']) if history['val_loss'] else None],
        'Final Train Loss': [history['train_loss'][-1] if history['train_loss'] else None],
        'Final Train Accuracy (%)': [history['train_acc'][-1] if history['train_acc'] else None],
        'Test Loss': [test_metrics['loss']],
        'Test Accuracy (%)': [test_metrics['accuracy']],
        'Test IoU': [test_metrics['iou']],
        'Test Dice': [test_metrics['dice']]
    }
    metrics_df = pd.DataFrame(final_metrics_summary)
    metrics_path = os.path.join(RESULTS_DIR, 'final_metrics_summary.csv')
    metrics_df.to_csv(metrics_path, index=False)
    print(f"\nFinal metrics summary saved to: {metrics_path}")

    # Plot training history
    plt.figure(figsize=(18, 6))
    plt.subplot(1, 2, 1)
    plt.plot(history['train_loss'], label='Training Loss')
    plt.plot(history['val_loss'], label='Validation Loss')
    plt.title('Teacher Model - Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)
    plt.subplot(1, 2, 2)
    plt.plot(history['train_acc'], label='Training Accuracy')
    plt.plot(history['val_acc'], label='Validation Accuracy')
    plt.title('Teacher Model - Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Pixel Accuracy (%)')
    plt.legend()
    plt.grid(True)
    plt.savefig(os.path.join(RESULTS_DIR, 'training_history_curves.png'))
    plt.close()

    # Plot results
    plot_segmentation_examples(all_images, all_true_masks, all_pred_masks)
    plot_confusion_matrix(all_true_masks, all_pred_masks)

if __name__ == "__main__":
    main()