# -*- coding: utf-8 -*-
"""dual_input_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cOoa9SxyJTguKIdm2-wdihn_s7NM9yO_
"""

"""
Dual-Input Classification (Original + Segmented Images).
Uses PyTorch with two backbones.
"""
# Imports and utils same as single_input

class DualInputDataset(Dataset):
    """Dataset for dual inputs."""
    def __init__(self, df, transforms=None):
        self.df = df
        self.transforms = transforms

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        orig_img = np.array(Image.open(row['original_path']).convert('RGB'))
        seg_img = np.array(Image.open(row['segmented_path']).convert('RGB'))
        if orig_img.ndim == 2:
            orig_img = np.stack([orig_img] * 3, axis=-1)
        if seg_img.ndim == 2:
            seg_img = np.stack([seg_img] * 3, axis=-1)
        label = torch.tensor(int(row['label']), dtype=torch.long)
        if self.transforms:
            trans_orig = self.transforms(image=orig_img)['image']
            trans_seg = self.transforms(image=seg_img)['image']
            return trans_orig, trans_seg, label
        return orig_img, seg_img, label

class DualInputModel(nn.Module):
    """Dual-input model with two backbones."""
    def __init__(self, model_name='efficientnet_b0', num_classes=3, dropout_rate=0.5):
        super().__init__()
        self.backbone1 = timm.create_model(model_name, pretrained=True, num_classes=0)  # Original
        self.backbone2 = timm.create_model(model_name, pretrained=True, num_classes=0)  # Segmented
        feature_dim = self.backbone1.num_features * 2
        self.head = nn.Sequential(
            nn.Linear(feature_dim, 512),
            nn.BatchNorm1d(512),
            nn.ReLU(),
            nn.Dropout(dropout_rate),
            nn.Linear(512, num_classes)
        )

    def forward(self, orig_img, seg_img):
        feat1 = self.backbone1(orig_img)
        feat2 = self.backbone2(seg_img)
        combined = torch.cat((feat1, feat2), dim=1)
        return self.head(combined)

# In main(): Load U-Net for segmentation first (as in original), generate segmented images.
# Then build df with 'original_path' and 'segmented_path'.
# Use DualInputDataset for dataloaders.
# Train/eval similar to single_input, but pass two images to model.

def main():
    # ... (similar to single_input, but add U-Net loading/generation)
    # For example:
    unet_path = 'outputs/segmentation/unet_model.keras'  # From segmentation.py
    # Load unet, segment images into segmented_dir
    # Then proceed with dual dataset
    pass

if __name__ == "__main__":
    main()