# -*- coding: utf-8 -*-
"""generate_masks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NMVBchClAzWdwEBOs1zAM45F6TuJECSR
"""

"""
Generate binary masks from annotated images for kidney segmentation.

This script processes annotated images to create binary masks by detecting yellow
and blue annotations, applying morphological operations, and filling the largest
contour. Visualizations of the mask generation process are saved for the first few
images to aid in verification.
"""

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
from pathlib import Path

# Configuration
DATA_DIR = "data/raw_data"
IMAGE_DIR = os.path.join(DATA_DIR, "images")
ANNOTATED_IMG_DIR = os.path.join(DATA_DIR, "annotated_data")
DEST_MASK_DIR = os.path.join(DATA_DIR, "masks")
VIS_DIR = "results/visualizations"
Path(DEST_MASK_DIR).mkdir(parents=True, exist_ok=True)
Path(VIS_DIR).mkdir(parents=True, exist_ok=True)

def generate_mask_from_annotated(annotated_path: str, output_mask_path: str, vis_path: str = None) -> tuple[bool, np.ndarray]:
    """
    Generate a binary mask from an annotated image.

    Args:
        annotated_path (str): Path to the annotated image.
        output_mask_path (str): Path to save the generated mask.
        vis_path (str, optional): Path to save visualization of the process.

    Returns:
        tuple[bool, np.ndarray]: Success flag and the generated mask (or None if failed).
    """
    try:
        # Read and preprocess image
        annotated_img = cv2.imread(annotated_path)
        if annotated_img is None:
            raise ValueError(f"Failed to load image: {annotated_path}")

        # Convert to HSV for color-based segmentation
        hsv_img = cv2.cvtColor(annotated_img, cv2.COLOR_BGR2HSV)

        # Define color ranges for yellow and blue annotations
        lower_yellow = np.array([20, 100, 100])
        upper_yellow = np.array([30, 255, 255])
        lower_blue = np.array([100, 100, 100])
        upper_blue = np.array([140, 255, 255])

        # Create masks for yellow and blue
        mask_yellow = cv2.inRange(hsv_img, lower_yellow, upper_yellow)
        mask_blue = cv2.inRange(hsv_img, lower_blue, upper_blue)

        # Combine masks
        combined_mask = cv2.bitwise_or(mask_yellow, mask_blue)

        # Apply morphological operations to clean noise and connect lines
        kernel = np.ones((3, 3), np.uint8)
        dilated_mask = cv2.dilate(combined_mask, kernel, iterations=2)
        refined_mask = cv2.morphologyEx(dilated_mask, cv2.MORPH_CLOSE, kernel, iterations=1)
        refined_mask = cv2.morphologyEx(refined_mask, cv2.MORPH_OPEN, kernel, iterations=1)

        # Detect and fill the largest contour
        contours, _ = cv2.findContours(refined_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        final_mask = np.zeros_like(refined_mask)
        if contours:
            largest_contour = max(contours, key=cv2.contourArea)
            cv2.fillPoly(final_mask, [largest_contour], 255)

        # Ensure binary format
        _, final_mask = cv2.threshold(final_mask, 127, 255, cv2.THRESH_BINARY)

        # Save the mask
        cv2.imwrite(output_mask_path, final_mask)

        # Generate visualization if requested
        if vis_path:
            fig, axs = plt.subplots(2, 4, figsize=(20, 10))
            fig.suptitle(f"Mask Generation Process for {os.path.basename(annotated_path)}", fontsize=16)

            axs[0, 0].imshow(cv2.cvtColor(annotated_img, cv2.COLOR_BGR2RGB))
            axs[0, 0].set_title('a) Input Annotated Image')
            axs[0, 0].axis('off')
            axs[0, 1].imshow(cv2.cvtColor(hsv_img, cv2.COLOR_HSV2RGB))
            axs[0, 1].set_title('b) HSV Converted')
            axs[0, 1].axis('off')
            axs[0, 2].imshow(mask_yellow, cmap='gray')
            axs[0, 2].set_title('c) Yellow Mask')
            axs[0, 2].axis('off')
            axs[0, 3].imshow(mask_blue, cmap='gray')
            axs[0, 3].set_title('d) Blue Mask')
            axs[0, 3].axis('off')
            axs[1, 0].imshow(combined_mask, cmap='gray')
            axs[1, 0].set_title('e) Combined Mask (Dilated)')
            axs[1, 0].axis('off')
            axs[1, 1].imshow(refined_mask, cmap='gray')
            axs[1, 1].set_title('f) Refined Mask (Morph Ops)')
            axs[1, 1].axis('off')
            axs[1, 2].imshow(final_mask, cmap='gray')
            axs[1, 2].set_title('g) Final Filled Mask')
            axs[1, 2].axis('off')
            axs[1, 3].axis('off')

            plt.tight_layout(rect=[0, 0.03, 1, 0.95])
            plt.savefig(vis_path)
            plt.close()

        return True, final_mask
    except Exception as e:
        print(f"Error processing {annotated_path}: {e}")
        return False, None

def main():
    """Process all annotated images to generate binary masks."""
    print("\n--- Finding Matching Annotated and Original Images ---")
    try:
        # Get list of base filenames (without extensions)
        original_files = {os.path.splitext(f)[0] for f in os.listdir(IMAGE_DIR)
                         if f.lower().endswith(('.jpg', '.jpeg', '.png'))}
        annotated_files = {os.path.splitext(f)[0] for f in os.listdir(ANNOTATED_IMG_DIR)
                          if f.lower().endswith(('.jpg', '.jpeg', '.png'))}

        # Find matching pairs
        matching_files = sorted(list(original_files.intersection(annotated_files)))
        if not matching_files:
            raise ValueError("No matching image-annotated pairs found. Check folder contents.")
        print(f"Found {len(matching_files)} matching image-annotated pairs. Example: {list(matching_files)[:5]}...")

        # Process each pair
        for idx, base_name in enumerate(tqdm(matching_files, desc="Generating Masks")):
            annotated_path = os.path.join(ANNOTATED_IMG_DIR, f"{base_name}.jpg")
            if not os.path.exists(annotated_path):
                annotated_path = os.path.join(ANNOTATED_IMG_DIR, f"{base_name}.png")

            output_mask_path = os.path.join(DEST_MASK_DIR, f"{base_name}.png")
            vis_path = os.path.join(VIS_DIR, f"{base_name}_process.png") if idx < 3 else None

            if not os.path.exists(annotated_path):
                print(f"Warning: Annotated image not found for {base_name} as JPG or PNG. Skipping.")
                continue

            generate_mask_from_annotated(annotated_path, output_mask_path, vis_path)

        print(f"\n✅ Mask generation completed. Generated masks saved in {DEST_MASK_DIR}")
        print(f"Visualizations saved in {VIS_DIR}")
    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    main()