# -*- coding: utf-8 -*-
"""segment_kidneys.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p0CNeY5EGMPfFfLbz1MuX4HFvHkz_ijX
"""

"""
Batch process image-mask pairs to extract segmented kidneys.

This script applies clean binary masks to original images to isolate kidney regions
and saves the segmented images. A few random samples are visualized for verification.
"""

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
from pathlib import Path

# Configuration
DATA_DIR = "data/raw_data"
IMAGES_DIR = os.path.join(DATA_DIR, "images")
MASKS_DIR = os.path.join(DATA_DIR, "masks")
SEGMENTED_KIDNEY_DIR = "data/segmented_kidneys"
Path(SEGMENTED_KIDNEY_DIR).mkdir(parents=True, exist_ok=True)

def generate_clean_mask(mask_path: str) -> np.ndarray:
    """
    Generate a clean binary mask from an annotation file.

    Args:
        mask_path (str): Path to the mask or annotated image.

    Returns:
        np.ndarray: Cleaned binary mask, or None if processing fails.
    """
    try:
        mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
        if mask is None:
            raise ValueError(f"Failed to load mask: {mask_path}")

        _, binary_mask = cv2.threshold(mask, 127, 255, cv2.THRESH_BINARY)
        kernel = np.ones((3, 3), np.uint8)
        cleaned_mask = cv2.morphologyEx(binary_mask, cv2.MORPH_CLOSE, kernel, iterations=2)
        contours, _ = cv2.findContours(cleaned_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        final_mask = np.zeros_like(cleaned_mask)
        if contours:
            largest_contour = max(contours, key=cv2.contourArea)
            cv2.drawContours(final_mask, [largest_contour], -1, color=255, thickness=cv2.FILLED)
        return final_mask
    except Exception as e:
        print(f"Error processing mask {mask_path}: {e}")
        return None

def main():
    """Process image-mask pairs to extract and save segmented kidneys."""
    print("\n--- Finding Matching Image-Mask Pairs for Processing ---")
    try:
        # Find matching files
        image_basenames = {os.path.splitext(f)[0] for f in os.listdir(IMAGES_DIR)
                          if f.lower().endswith(('.jpg', '.jpeg', '.png'))}
        mask_basenames = {os.path.splitext(f)[0] for f in os.listdir(MASKS_DIR)
                         if f.lower().endswith(('.jpg', '.jpeg', '.png'))}
        matching_files = sorted(list(image_basenames.intersection(mask_basenames)))

        if not matching_files:
            raise ValueError("No matching image and mask files were found. Please check your directories.")
        print(f"Found {len(matching_files)} matching image-mask pairs to process.")

        processed_records = []
        for basename in tqdm(matching_files, desc="Processing Image Pairs"):
            image_path = None
            for ext in ['.jpg', '.jpeg', '.png']:
                if os.path.exists(os.path.join(IMAGES_DIR, basename + ext)):
                    image_path = os.path.join(IMAGES_DIR, basename + ext)
                    break

            mask_path = None
            for ext in ['.jpg', '.jpeg', '.png']:
                if os.path.exists(os.path.join(MASKS_DIR, basename + ext)):
                    mask_path = os.path.join(MASKS_DIR, basename + ext)
                    break

            if not image_path or not mask_path:
                print(f"Warning: Could not find full pair for {basename}. Skipping.")
                continue

            clean_mask = generate_clean_mask(mask_path)
            if clean_mask is not None:
                original_image = cv2.imread(image_path)
                target_height, target_width, _ = original_image.shape
                resized_mask = cv2.resize(clean_mask, (target_width, target_height), interpolation=cv2.INTER_NEAREST)
                segmented_kidney = cv2.bitwise_and(original_image, original_image, mask=resized_mask)

                output_filename = os.path.basename(image_path)
                output_path = os.path.join(SEGMENTED_KIDNEY_DIR, output_filename)
                cv2.imwrite(output_path, segmented_kidney)

                processed_records.append({
                    "original": image_path,
                    "mask": mask_path,
                    "segmented": output_path
                })

        print(f"\n✅ Batch processing complete. {len(processed_records)} segmented kidneys saved.")

        # Visualize samples
        if processed_records:
            print("\n--- Displaying Verification Samples ---")
            num_samples_to_show = min(5, len(processed_records))
            sample_indices = np.random.choice(len(processed_records), num_samples_to_show, replace=False)

            for i in sample_indices:
                record = processed_records[i]
                original_image = cv2.imread(record['original'])
                clean_mask = generate_clean_mask(record['mask'])
                segmented_kidney = cv2.imread(record['segmented'])

                fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(18, 6))
                fig.suptitle(f"Verification for: {os.path.basename(record['original'])}", fontsize=16)
                ax1.imshow(cv2.cvtColor(original_image, cv2.COLOR_BGR2RGB))
                ax1.set_title("1. Original Image")
                ax1.axis('off')
                ax2.imshow(clean_mask, cmap='gray')
                ax2.set_title("2. Generated Clean Mask")
                ax2.axis('off')
                ax3.imshow(cv2.cvtColor(segmented_kidney, cv2.COLOR_BGR2RGB))
                ax3.set_title("3. Final Segmented Kidney")
                ax3.axis('off')
                plt.tight_layout(rect=[0, 0.03, 1, 0.95])
                plt.savefig(os.path.join(SEGMENTED_KIDNEY_DIR, f"verification_{os.path.basename(record['original'])}"))
                plt.close()

    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    main()