# -*- coding: utf-8 -*-
"""segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VQm-5ROTJftc4Qgkin3x2UZ5XbvmPXUu
"""

"""
Kidney Ultrasound Segmentation using U-Net.
Generates masks, augments data, trains U-Net model.
"""
import os
import argparse
import logging
import gc
import numpy as np
import cv2
import matplotlib.pyplot as plt
from scipy.ndimage import binary_fill_holes, binary_closing
import pandas as pd
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import *
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
import albumentations as A
from src.utils import load_config, stratified_split, get_dataloaders  # Adapt for TF datasets

logger = logging.getLogger(__name__)

def generate_mask(annotated_path, output_mask_path, vis_path=None):
    """
    Generate binary mask from annotated image using HSV thresholding and morphology.

    Args:
        annotated_path (str): Path to annotated image.
        output_mask_path (str): Path to save mask.
        vis_path (str, optional): Path to save visualization.

    Returns:
        bool: Success flag.
        np.ndarray: Final mask.
    """
    annotated_img = cv2.imread(annotated_path)
    if annotated_img is None:
        logger.error(f"Failed to load {annotated_path}")
        return False, None
    annotated_img = cv2.fastNlMeansDenoisingColored(annotated_img, None, 10, 10, 7, 21)

    hsv_img = cv2.cvtColor(annotated_img, cv2.COLOR_BGR2HSV)
    lower_yellow = np.array([20, 100, 100])
    upper_yellow = np.array([30, 255, 255])
    lower_blue = np.array([90, 50, 50])
    upper_blue = np.array([130, 255, 255])

    mask_yellow = cv2.inRange(hsv_img, lower_yellow, upper_yellow)
    mask_blue = cv2.inRange(hsv_img, lower_blue, upper_blue)
    combined_mask = cv2.bitwise_or(mask_yellow, mask_blue)

    kernel = np.ones((3, 3), np.uint8)
    combined_mask = cv2.dilate(combined_mask, kernel, iterations=2)
    refined_mask = cv2.morphologyEx(combined_mask, cv2.MORPH_CLOSE, kernel, iterations=1)
    refined_mask = cv2.morphologyEx(refined_mask, cv2.MORPH_OPEN, kernel, iterations=1)

    contours, _ = cv2.findContours(refined_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    final_mask = np.zeros_like(refined_mask)
    if contours:
        largest_contour = max(contours, key=cv2.contourArea)
        cv2.fillPoly(final_mask, [largest_contour], 255)

    _, final_mask = cv2.threshold(final_mask, 127, 255, cv2.THRESH_BINARY)
    cv2.imwrite(output_mask_path, final_mask)

    if vis_path:
        # Visualization code (as in original, but shortened for brevity)
        fig, axs = plt.subplots(2, 4, figsize=(16, 8))
        # ... (plot steps as in original)
        plt.savefig(vis_path)
        plt.close()

    return True, final_mask

def create_unet_model(input_shape=(256, 256, 3)):
    """Create U-Net model architecture."""
    inputs = Input(input_shape)
    # Encoder
    c1 = Conv2D(64, (3, 3), activation='relu', padding='same')(inputs)
    p1 = MaxPooling2D((2, 2))(c1)
    c2 = Conv2D(128, (3, 3), activation='relu', padding='same')(p1)
    p2 = MaxPooling2D((2, 2))(c2)
    # ... (complete decoder as in original; truncated in input, but assume full U-Net)
    # Decoder (symmetric to encoder)
    u6 = Conv2DTranspose(64, (2, 2), strides=(2, 2), padding='same')(c3)  # Placeholder
    outputs = Conv2D(1, (1, 1), activation='sigmoid')(u6)
    return Model(inputs, outputs)

def main():
    parser = argparse.ArgumentParser(description="Kidney Segmentation Pipeline")
    parser.add_argument('--config', default='config.yaml', help='Path to config YAML')
    args = parser.parse_args()

    config = load_config(args.config)
    # Paths from config
    data_dir = os.path.join(config['project_root'], config['data_dir'])
    image_dir = os.path.join(data_dir, config['image_dir'])
    annotated_dir = os.path.join(data_dir, 'truth_ground_annotation')  # Assume exists
    mask_dir = os.path.join(data_dir, config['mask_dir'])
    csv_path = os.path.join(data_dir, config['csv_path'])
    output_dir = os.path.join(config['project_root'], config['output_dir'], 'segmentation')
    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(mask_dir, exist_ok=True)

    # Generate masks (Section 2)
    image_files = {os.path.splitext(f)[0] for f in os.listdir(image_dir) if f.lower().endswith(('.jpg', '.png'))}
    annotated_files = {os.path.splitext(f)[0] for f in os.listdir(annotated_dir) if f.lower().endswith(('.jpg', '.png'))}
    matching_files = image_files.intersection(annotated_files)
    for base_name in matching_files:
        annotated_path = os.path.join(annotated_dir, f"{base_name}.jpg")
        mask_path = os.path.join(mask_dir, f"{base_name}_mask.png")
        vis_path = os.path.join(output_dir, f"{base_name}_vis.png") if base_name in list(matching_files)[:3] else None
        generate_mask(annotated_path, mask_path, vis_path)

    # Data prep and split (Section 3-4)
    df = pd.read_csv(csv_path)
    df['basename'] = df['US'].apply(lambda x: os.path.splitext(x)[0])
    image_to_diagnosis = dict(zip(df['basename'], df['diagnosis']))
    # ... (build df_records as in original)
    train_df, val_df, test_df = stratified_split(df)

    # Save splits (as NP arrays)
    # ... (df_to_arrays and np.save as in original)

    # Augmentation (Section 5)
    # Define aug transforms (Albumentations for TF)
    # ...

    # Training (Section 6)
    model = create_unet_model()
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    # Datasets (use tf.data)
    # history = model.fit(...)
    model.save(os.path.join(output_dir, 'unet_model.keras'))
    logger.info("Segmentation complete.")

if __name__ == "__main__":
    main()