# -*- coding: utf-8 -*-
"""single_input_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CV7fT4D_cPsKLvbHw-EgGxAWHxO5On13
"""

"""
Single-Input Classification for Kidney Ultrasound (Non-Segmented Images).
Uses PyTorch with multiple backbones (EfficientNet, ResNet, etc.).
"""
import os
import argparse
import logging
import time
import json
import pickle
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import timm
from tqdm import tqdm
from src.utils import load_config, stratified_split, KidneyDataset, get_dataloaders

logger = logging.getLogger(__name__)

class SingleInputModel(nn.Module):
    """Single-input classification model with timm backbone."""
    def __init__(self, model_name='efficientnet_b0', num_classes=3, dropout_rate=0.5):
        super().__init__()
        self.backbone = timm.create_model(model_name, pretrained=True, num_classes=0)
        feature_dim = self.backbone.num_features
        self.head = nn.Sequential(
            nn.Linear(feature_dim, 512),
            nn.BatchNorm1d(512),
            nn.ReLU(),
            nn.Dropout(dropout_rate),
            nn.Linear(512, num_classes)
        )

    def forward(self, image):
        features = self.backbone(image)
        return self.head(features)

def plot_training_history(history, model_name, output_dir):
    """Plot loss and accuracy curves."""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
    ax1.plot(history['train_loss'], label='Train Loss')
    ax1.plot(history['val_loss'], label='Val Loss')
    ax1.legend(); ax1.grid(True)
    ax2.plot(history['train_accuracy'], label='Train Acc')
    ax2.plot(history['val_accuracy'], label='Val Acc')
    ax2.legend(); ax2.grid(True)
    plt.savefig(os.path.join(output_dir, f'{model_name}_history.png'))
    plt.close()

def train_model(model, train_loader, val_loader, epochs, lr, output_dir, model_name):
    """Train a single model."""
    optimizer = optim.Adam(model.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, 'max', patience=5, factor=0.5)
    history = {'train_loss': [], 'val_loss': [], 'train_accuracy': [], 'val_accuracy': []}
    best_val_acc = 0.0

    for epoch in range(epochs):
        # Train loop
        model.train()
        train_loss, train_correct, train_total = 0.0, 0, 0
        for images, labels in tqdm(train_loader, desc=f'Epoch {epoch+1}'):
            images, labels = images.to(DEVICE), labels.to(DEVICE)
            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            train_loss += loss.item() * images.size(0)
            _, predicted = torch.max(outputs, 1)
            train_total += labels.size(0)
            train_correct += (predicted == labels).sum().item()
        train_acc = 100 * train_correct / train_total
        history['train_loss'].append(train_loss / train_total)
        history['train_accuracy'].append(train_acc)

        # Val loop
        model.eval()
        val_loss, val_correct, val_total = 0.0, 0, 0
        with torch.no_grad():
            for images, labels in val_loader:
                images, labels = images.to(DEVICE), labels.to(DEVICE)
                outputs = model(images)
                loss = criterion(outputs, labels)
                val_loss += loss.item() * images.size(0)
                _, predicted = torch.max(outputs, 1)
                val_total += labels.size(0)
                val_correct += (predicted == labels).sum().item()
        val_acc = 100 * val_correct / val_total
        history['val_loss'].append(val_loss / val_total)
        history['val_accuracy'].append(val_acc)
        scheduler.step(val_acc)

        if val_acc > best_val_acc:
            best_val_acc = val_acc
            torch.save(model.state_dict(), os.path.join(output_dir, f'best_{model_name}.pth'))

        logger.info(f'Epoch {epoch+1}: Train Loss {train_loss/train_total:.4f}, Acc {train_acc:.2f}%; '
                    f'Val Loss {val_loss/val_total:.4f}, Acc {val_acc:.2f}%')

    torch.save(model.state_dict(), os.path.join(output_dir, f'final_{model_name}.pth'))
    with open(os.path.join(output_dir, f'{model_name}_history.pkl'), 'wb') as f:
        pickle.dump(history, f)
    plot_training_history(history, model_name, output_dir)
    return history

def evaluate_model(model, test_loader, classes, output_dir, model_name):
    """Evaluate model on test set."""
    model.eval()
    all_labels, all_preds = [], []
    test_loss, test_correct, test_total = 0.0, 0, 0
    criterion = nn.CrossEntropyLoss()
    with torch.no_grad():
        for images, labels in test_loader:
            images, labels = images.to(DEVICE), labels.to(DEVICE)
            outputs = model(images)
            loss = criterion(outputs, labels)
            test_loss += loss.item() * images.size(0)
            _, predicted = torch.max(outputs, 1)
            test_total += labels.size(0)
            test_correct += (predicted == labels).sum().item()
            all_labels.extend(labels.cpu().numpy())
            all_preds.extend(predicted.cpu().numpy())

    test_acc = 100 * test_correct / test_total
    report = classification_report(all_labels, all_preds, target_names=classes, output_dict=True)
    metrics = {
        'test_loss': test_loss / test_total,
        'test_accuracy': test_acc,
        'macro_f1': report['macro avg']['f1-score'],
        # ... (add more as in original)
    }

    # Confusion matrix plot
    cm = confusion_matrix(all_labels, all_preds)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=classes, yticklabels=classes)
    plt.savefig(os.path.join(output_dir, f'cm_{model_name}.png'))
    plt.close()

    with open(os.path.join(output_dir, 'metrics.json'), 'w') as f:
        json.dump(metrics, f, indent=4)
    logger.info(f'{model_name} Test Acc: {test_acc:.2f}%')

def main():
    parser = argparse.ArgumentParser(description="Single-Input Classification")
    parser.add_argument('--config', default='config.yaml', help='Path to config')
    parser.add_argument('--output_dir', default='outputs/single_input', help='Output directory')
    args = parser.parse_args()

    config = load_config(args.config)
    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
    os.makedirs(args.output_dir, exist_ok=True)

    # Data prep
    image_dir = os.path.join(config['project_root'], config['data_dir'], config['image_dir'])
    csv_path = os.path.join(config['project_root'], config['data_dir'], config['csv_path'])
    labels_df = pd.read_csv(csv_path)
    labels_df['basename'] = labels_df['US'].apply(lambda x: os.path.splitext(x)[0])
    basename_to_diagnosis = dict(zip(labels_df['basename'], labels_df['diagnosis']))
    # Build df (as in original)
    # ...

    train_df, val_df, test_df = stratified_split(df)

    # Transforms
    train_transforms = A.Compose([
        A.Resize(config['cls_img_size'], config['cls_img_size']),
        A.HorizontalFlip(p=0.5),
        A.VerticalFlip(p=0.5),
        A.Rotate(limit=15, p=0.5),
        A.CoarseDropout(p=0.5),
        A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
        ToTensorV2(),
    ])
    val_test_transforms = A.Compose([
        A.Resize(config['cls_img_size'], config['cls_img_size']),
        A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
        ToTensorV2(),
    ])

    train_loader, val_loader, test_loader = get_dataloaders(
        train_df, val_df, test_df, config['batch_size'], train_transforms, val_test_transforms
    )

    models_to_train = config['models_to_train']
    classes = ['Normal', 'CKD', 'AKI']

    for model_nickname in models_to_train:
        model_name = {  # Map nicknames to timm names
            'SwinTransformer': 'swin_tiny_patch4_window7_224',
            # ...
        }[model_nickname]
        model = SingleInputModel(model_name, config['num_classes']).to(DEVICE)
        history = train_model(model, train_loader, val_loader, config['epochs'], config['learning_rate'], args.output_dir, model_nickname)
        evaluate_model(model, test_loader, classes, args.output_dir, model_nickname)

if __name__ == "__main__":
    main()