# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-BSAGGRQd4J4o23WgiC007lj-HcaDL4J
"""

"""
Utility functions for kidney ultrasound project.
"""
import os
import yaml
import logging
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from PIL import Image
import torch
from torch.utils.data import Dataset, DataLoader
import albumentations as A
from albumentations.pytorch import ToTensorV2
from tqdm import tqdm

# Setup logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

def load_config(config_path='config.yaml'):
    """Load configuration from YAML file."""
    with open(config_path, 'r') as f:
        return yaml.safe_load(f)

def stratified_split(df, test_size=0.20, val_size=0.15, random_state=42):
    """Perform stratified patient-level split."""
    patient_df = df.drop_duplicates(subset='patient_id').set_index('patient_id')
    train_val_patients, test_patients = train_test_split(
        patient_df.index, test_size=test_size, random_state=random_state,
        stratify=patient_df['label']
    )
    train_patients, val_patients = train_test_split(
        train_val_patients, test_size=val_size / (1 - test_size), random_state=random_state,
        stratify=patient_df.loc[train_val_patients]['label']
    )
    train_df = df[df['patient_id'].isin(train_patients)]
    val_df = df[df['patient_id'].isin(val_patients)]
    test_df = df[df['patient_id'].isin(test_patients)]
    return train_df, val_df, test_df

class KidneyDataset(Dataset):
    """Base dataset for kidney images."""
    def __init__(self, df, transforms=None):
        self.df = df
        self.transforms = transforms

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        image = np.array(Image.open(row['image_path']).convert('RGB'))
        if image.ndim == 2:
            image = np.stack([image] * 3, axis=-1)
        label = torch.tensor(int(row['label']), dtype=torch.long)
        if self.transforms:
            transformed = self.transforms(image=image)['image']
            return transformed, label
        return image, label

def get_dataloaders(train_df, val_df, test_df, batch_size=32, transforms_train=None, transforms_valtest=None):
    """Create DataLoaders."""
    train_dataset = KidneyDataset(train_df, transforms_train)
    val_dataset = KidneyDataset(val_df, transforms_valtest)
    test_dataset = KidneyDataset(test_df, transforms_valtest)
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)
    return train_loader, val_loader, test_loader